# Generated by Django 4.0.4 on 2022-06-22 17:52

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_reviews_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='summary',
            field=models.TextField(default='Podsumowanie', max_length=1024),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='review_image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='lead',
            field=models.TextField(default='Zapowiedź', max_length=1024),
        ),
    ]
