# Generated by Django 4.0.4 on 2022-06-23 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0021_rating_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.rating')),
            ],
        ),
    ]
