# Generated by Django 4.0.4 on 2022-05-06 08:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tytuł gry', max_length=128)),
                ('developer', models.CharField(help_text='Developer', max_length=128)),
                ('description', models.TextField(help_text='Opis gry', max_length=512)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('image_link', models.CharField(blank=True, help_text='Link do zdjęcia', max_length=512, null=True)),
                ('trailer', models.CharField(blank=True, help_text='Link do trailera gry', max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True, help_text='Twoja opinia', max_length=256, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
