# Generated by Django 4.0.4 on 2022-05-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_alter_rating_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(help_text='Opis gry', max_length=1024),
        ),
        migrations.AlterField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True, help_text='Twoja opinia', max_length=512, null=True),
        ),
    ]
