# Generated by Django 4.0.4 on 2022-05-24 15:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Opis gry', max_length=1024),
        ),
    ]
