# Generated by Django 4.0.4 on 2022-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(help_text='Opis gry', max_length=1024),
        ),
    ]
