# Generated by Django 4.0.4 on 2022-05-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/games/'),
        ),
    ]
