# Generated by Django 4.0.4 on 2022-06-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='accepted',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
